/* File: fsamodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Jun  9 03:48:10 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fsa_error;
static PyObject *fsa_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(fsa_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = fsa_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = fsa_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** init_problem ********************************/
static char doc_f2py_rout_fsa_problem_init_problem[] = "\
init_problem()\n\nWrapper for ``init_problem``.\
\n";
/*  */
static PyObject *f2py_rout_fsa_problem_init_problem(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":fsa.problem.init_problem",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of init_problem ****************************/

/******************************** loadexample ********************************/
static char doc_f2py_rout_fsa_problem_loadexample[] = "\
loadexample(filename)\n\nWrapper for ``loadexample``.\
\n\nParameters\n----------\n"
"filename : input string(len=-1)";
/*  */
static PyObject *f2py_rout_fsa_problem_loadexample(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  static char *capi_kwlist[] = {"filename",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:fsa.problem.loadexample",\
    capi_kwlist,&filename_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 1st argument `filename' of fsa.problem.loadexample to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(filename,slen(filename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of loadexample *****************************/

/********************************** get_cost **********************************/
static char doc_f2py_rout_fsa_problem_get_cost[] = "\
cost = get_cost(config)\n\nWrapper for ``get_cost``.\
\n\nParameters\n----------\n"
"config : input rank-1 array('i') with bounds (num_spin)\n"
"\nReturns\n-------\n"
"cost : float";
/*  */
static PyObject *f2py_rout_fsa_problem_get_cost(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int num_spin = 0;
  int *config = NULL;
  npy_intp config_Dims[1] = {-1};
  const int config_Rank = 1;
  PyArrayObject *capi_config_tmp = NULL;
  int capi_config_intent = 0;
  PyObject *config_capi = Py_None;
  float cost = 0;
  static char *capi_kwlist[] = {"config",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:fsa.problem.get_cost",\
    capi_kwlist,&config_capi))
    return NULL;
/*frompyobj*/
  /* Processing auxiliary variable num_spin */
  num_spin = len(config);
  /* Processing variable cost */
  /* Processing variable config */
  ;
  capi_config_intent |= F2PY_INTENT_IN;
  capi_config_tmp = array_from_pyobj(NPY_INT,config_Dims,config_Rank,capi_config_intent,config_capi);
  if (capi_config_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting 1st argument `config' of fsa.problem.get_cost to C/Fortran array" );
  } else {
    config = (int *)(PyArray_DATA(capi_config_tmp));

  CHECKSCALAR(len(config)>=num_spin,"len(config)>=num_spin","#nth# num_spin","get_cost:num_spin=%d",num_spin) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(config,&cost);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",cost);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(config)>=num_spin)*/
  if((PyObject *)capi_config_tmp!=config_capi) {
    Py_XDECREF(capi_config_tmp); }
  }  /*if (capi_config_tmp == NULL) ... else of config*/
  /* End of cleaning variable config */
  /* End of cleaning variable cost */
  /* End of cleaning variable num_spin */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of get_cost ******************************/

/********************************** propose **********************************/
static char doc_f2py_rout_fsa_problem_propose[] = "\
ispin,delta = propose(config,field)\n\nWrapper for ``propose``.\
\n\nParameters\n----------\n"
"config : input rank-1 array('i') with bounds (num_spin)\n"
"field : input rank-1 array('f') with bounds (num_spin)\n"
"\nReturns\n-------\n"
"ispin : int\n"
"delta : float";
/*  */
static PyObject *f2py_rout_fsa_problem_propose(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int num_spin = 0;
  int *config = NULL;
  npy_intp config_Dims[1] = {-1};
  const int config_Rank = 1;
  PyArrayObject *capi_config_tmp = NULL;
  int capi_config_intent = 0;
  PyObject *config_capi = Py_None;
  float *field = NULL;
  npy_intp field_Dims[1] = {-1};
  const int field_Rank = 1;
  PyArrayObject *capi_field_tmp = NULL;
  int capi_field_intent = 0;
  PyObject *field_capi = Py_None;
  int ispin = 0;
  float delta = 0;
  static char *capi_kwlist[] = {"config","field",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:fsa.problem.propose",\
    capi_kwlist,&config_capi,&field_capi))
    return NULL;
/*frompyobj*/
  /* Processing auxiliary variable num_spin */
  num_spin = len(config);
  /* Processing variable delta */
  /* Processing variable ispin */
  /* Processing variable config */
  ;
  capi_config_intent |= F2PY_INTENT_IN;
  capi_config_tmp = array_from_pyobj(NPY_INT,config_Dims,config_Rank,capi_config_intent,config_capi);
  if (capi_config_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting 1st argument `config' of fsa.problem.propose to C/Fortran array" );
  } else {
    config = (int *)(PyArray_DATA(capi_config_tmp));

  CHECKSCALAR(len(config)>=num_spin,"len(config)>=num_spin","#nth# num_spin","propose:num_spin=%d",num_spin) {
  /* Processing variable field */
  field_Dims[0]=num_spin;
  capi_field_intent |= F2PY_INTENT_IN;
  capi_field_tmp = array_from_pyobj(NPY_FLOAT,field_Dims,field_Rank,capi_field_intent,field_capi);
  if (capi_field_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting 2nd argument `field' of fsa.problem.propose to C/Fortran array" );
  } else {
    field = (float *)(PyArray_DATA(capi_field_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(config,field,&ispin,&delta);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("if",ispin,delta);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_field_tmp!=field_capi) {
    Py_XDECREF(capi_field_tmp); }
  }  /*if (capi_field_tmp == NULL) ... else of field*/
  /* End of cleaning variable field */
  } /*CHECKSCALAR(len(config)>=num_spin)*/
  if((PyObject *)capi_config_tmp!=config_capi) {
    Py_XDECREF(capi_config_tmp); }
  }  /*if (capi_config_tmp == NULL) ... else of config*/
  /* End of cleaning variable config */
  /* End of cleaning variable ispin */
  /* End of cleaning variable delta */
  /* End of cleaning variable num_spin */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of propose *******************************/

/*********************************** accept ***********************************/
static char doc_f2py_rout_fsa_problem_accept[] = "\
accept(ispin,config,field)\n\nWrapper for ``accept``.\
\n\nParameters\n----------\n"
"ispin : input int\n"
"config : in/output rank-1 array('i') with bounds (num_spin)\n"
"field : in/output rank-1 array('f') with bounds (num_spin)";
/*  */
static PyObject *f2py_rout_fsa_problem_accept(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int num_spin = 0;
  int ispin = 0;
  PyObject *ispin_capi = Py_None;
  int *config = NULL;
  npy_intp config_Dims[1] = {-1};
  const int config_Rank = 1;
  PyArrayObject *capi_config_tmp = NULL;
  int capi_config_intent = 0;
  PyObject *config_capi = Py_None;
  float *field = NULL;
  npy_intp field_Dims[1] = {-1};
  const int field_Rank = 1;
  PyArrayObject *capi_field_tmp = NULL;
  int capi_field_intent = 0;
  PyObject *field_capi = Py_None;
  static char *capi_kwlist[] = {"ispin","config","field",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:fsa.problem.accept",\
    capi_kwlist,&ispin_capi,&config_capi,&field_capi))
    return NULL;
/*frompyobj*/
  /* Processing auxiliary variable num_spin */
  num_spin = len(config);
  /* Processing variable ispin */
    f2py_success = int_from_pyobj(&ispin,ispin_capi,"fsa.problem.accept() 1st argument (ispin) can't be converted to int");
  if (f2py_success) {
  /* Processing variable config */
  ;
  capi_config_intent |= F2PY_INTENT_INOUT;
  capi_config_tmp = array_from_pyobj(NPY_INT,config_Dims,config_Rank,capi_config_intent,config_capi);
  if (capi_config_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting 2nd argument `config' of fsa.problem.accept to C/Fortran array" );
  } else {
    config = (int *)(PyArray_DATA(capi_config_tmp));

  CHECKSCALAR(len(config)>=num_spin,"len(config)>=num_spin","#nth# num_spin","accept:num_spin=%d",num_spin) {
  /* Processing variable field */
  field_Dims[0]=num_spin;
  capi_field_intent |= F2PY_INTENT_INOUT;
  capi_field_tmp = array_from_pyobj(NPY_FLOAT,field_Dims,field_Rank,capi_field_intent,field_capi);
  if (capi_field_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting 3rd argument `field' of fsa.problem.accept to C/Fortran array" );
  } else {
    field = (float *)(PyArray_DATA(capi_field_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ispin,config,field);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_field_tmp!=field_capi) {
    Py_XDECREF(capi_field_tmp); }
  }  /*if (capi_field_tmp == NULL) ... else of field*/
  /* End of cleaning variable field */
  } /*CHECKSCALAR(len(config)>=num_spin)*/
  if((PyObject *)capi_config_tmp!=config_capi) {
    Py_XDECREF(capi_config_tmp); }
  }  /*if (capi_config_tmp == NULL) ... else of config*/
  /* End of cleaning variable config */
  } /*if (f2py_success) of ispin*/
  /* End of cleaning variable ispin */
  /* End of cleaning variable num_spin */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of accept *******************************/

/***************************** get_random_config *****************************/
static char doc_f2py_rout_fsa_problem_get_random_config[] = "\
config,field = get_random_config()\n\nWrapper for ``get_random_config``.\
\n\nReturns\n-------\n"
"config : rank-1 array('i') with bounds (num_spin)\n"
"field : rank-1 array('f') with bounds (num_spin)";
/*  */
static PyObject *f2py_rout_fsa_problem_get_random_config(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int num_spin = 0;
  int *config = NULL;
  npy_intp config_Dims[1] = {-1};
  const int config_Rank = 1;
  PyArrayObject *capi_config_tmp = NULL;
  int capi_config_intent = 0;
  float *field = NULL;
  npy_intp field_Dims[1] = {-1};
  const int field_Rank = 1;
  PyArrayObject *capi_field_tmp = NULL;
  int capi_field_intent = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":fsa.problem.get_random_config",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing auxiliary variable num_spin */
  /* Processing variable field */
  field_Dims[0]=num_spin;
  capi_field_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_field_tmp = array_from_pyobj(NPY_FLOAT,field_Dims,field_Rank,capi_field_intent,Py_None);
  if (capi_field_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting hidden `field' of fsa.problem.get_random_config to C/Fortran array" );
  } else {
    field = (float *)(PyArray_DATA(capi_field_tmp));

  /* Processing variable config */
  config_Dims[0]=num_spin;
  capi_config_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_config_tmp = array_from_pyobj(NPY_INT,config_Dims,config_Rank,capi_config_intent,Py_None);
  if (capi_config_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fsa_error,"failed in converting hidden `config' of fsa.problem.get_random_config to C/Fortran array" );
  } else {
    config = (int *)(PyArray_DATA(capi_config_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(config,field);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_config_tmp,capi_field_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_config_tmp == NULL) ... else of config*/
  /* End of cleaning variable config */
  }  /*if (capi_field_tmp == NULL) ... else of field*/
  /* End of cleaning variable field */
  /* End of cleaning variable num_spin */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of get_random_config **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_problem_def[] = {
  {"jmat",2,{{300,300}},NPY_FLOAT},
  {"num_tempscales",0,{{-1}},NPY_INT},
  {"num_spin",0,{{-1}},NPY_INT},
  {"nms",0,{{-1}},NPY_INT},
  {"tempscales",1,{{64}},NPY_FLOAT},
  {"init_problem",-1,{{-1}},0,NULL,(void *)f2py_rout_fsa_problem_init_problem,doc_f2py_rout_fsa_problem_init_problem},
  {"loadexample",-1,{{-1}},0,NULL,(void *)f2py_rout_fsa_problem_loadexample,doc_f2py_rout_fsa_problem_loadexample},
  {"get_cost",-1,{{-1}},0,NULL,(void *)f2py_rout_fsa_problem_get_cost,doc_f2py_rout_fsa_problem_get_cost},
  {"propose",-1,{{-1}},0,NULL,(void *)f2py_rout_fsa_problem_propose,doc_f2py_rout_fsa_problem_propose},
  {"accept",-1,{{-1}},0,NULL,(void *)f2py_rout_fsa_problem_accept,doc_f2py_rout_fsa_problem_accept},
  {"get_random_config",-1,{{-1}},0,NULL,(void *)f2py_rout_fsa_problem_get_random_config,doc_f2py_rout_fsa_problem_get_random_config},
  {NULL}
};

static void f2py_setup_problem(char *jmat,char *num_tempscales,char *num_spin,char *nms,char *tempscales,char *init_problem,char *loadexample,char *get_cost,char *propose,char *accept,char *get_random_config) {
  int i_f2py=0;
  f2py_problem_def[i_f2py++].data = jmat;
  f2py_problem_def[i_f2py++].data = num_tempscales;
  f2py_problem_def[i_f2py++].data = num_spin;
  f2py_problem_def[i_f2py++].data = nms;
  f2py_problem_def[i_f2py++].data = tempscales;
  f2py_problem_def[i_f2py++].data = init_problem;
  f2py_problem_def[i_f2py++].data = loadexample;
  f2py_problem_def[i_f2py++].data = get_cost;
  f2py_problem_def[i_f2py++].data = propose;
  f2py_problem_def[i_f2py++].data = accept;
  f2py_problem_def[i_f2py++].data = get_random_config;
}
extern void F_FUNC(f2pyinitproblem,F2PYINITPROBLEM)(void (*)(char*,char*,char*,char*,char*,char *,char *,char *,char *,char *,char *));
static void f2py_init_problem(void) {
  F_FUNC(f2pyinitproblem,F2PYINITPROBLEM)(f2py_setup_problem);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "fsa",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_fsa(void) {
#else
#define RETVAL
PyMODINIT_FUNC initfsa(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = fsa_module = PyModule_Create(&moduledef);
#else
  m = fsa_module = Py_InitModule("fsa", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module fsa (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'fsa' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  problem --- jmat,num_tempscales,num_spin,nms,tempscales,init_problem(),loadexample(),get_cost(),propose(),accept(),get_random_config()"".");
  PyDict_SetItemString(d, "__doc__", s);
  fsa_error = PyErr_NewException ("fsa.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));






/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "problem", PyFortranObject_New(f2py_problem_def,f2py_init_problem));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"fsa");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
