!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_qsort_c_module_quicksort_fi (A, B, f2py_A_d0, &
     &f2py_B_d0)
      use qsort_c_module, only : quicksort_fi
      integer f2py_A_d0
      integer f2py_B_d0
      real A(f2py_A_d0)
      integer B(f2py_B_d0)
      call quicksort_fi(A, B)
      end subroutine f2pywrap_qsort_c_module_quicksort_fi
      subroutine f2pywrap_qsort_c_module_partition_fi (A, B, marker, f2p&
     &y_A_d0, f2py_B_d0)
      use qsort_c_module, only : partition_fi
      integer marker
      integer f2py_A_d0
      integer f2py_B_d0
      real A(f2py_A_d0)
      integer B(f2py_B_d0)
      call partition_fi(A, B, marker)
      end subroutine f2pywrap_qsort_c_module_partition_fi
      subroutine f2pywrap_qsort_c_module_quicksort_ii (A, B, f2py_A_d0, &
     &f2py_B_d0)
      use qsort_c_module, only : quicksort_ii
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      integer B(f2py_B_d0)
      call quicksort_ii(A, B)
      end subroutine f2pywrap_qsort_c_module_quicksort_ii
      subroutine f2pywrap_qsort_c_module_Partition_ii (A, B, marker, f2p&
     &y_A_d0, f2py_B_d0)
      use qsort_c_module, only : Partition_ii
      integer marker
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      integer B(f2py_B_d0)
      call Partition_ii(A, B, marker)
      end subroutine f2pywrap_qsort_c_module_Partition_ii
      subroutine f2pywrap_qsort_c_module_quicksort_if (A, B, f2py_A_d0, &
     &f2py_B_d0)
      use qsort_c_module, only : quicksort_if
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      real B(f2py_B_d0)
      call quicksort_if(A, B)
      end subroutine f2pywrap_qsort_c_module_quicksort_if
      subroutine f2pywrap_qsort_c_module_Partition_if (A, B, marker, f2p&
     &y_A_d0, f2py_B_d0)
      use qsort_c_module, only : Partition_if
      integer marker
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      real B(f2py_B_d0)
      call Partition_if(A, B, marker)
      end subroutine f2pywrap_qsort_c_module_Partition_if
      
      subroutine f2pyinitqsort_c_module(f2pysetupfunc)
      interface 
      subroutine f2pywrap_qsort_c_module_quicksort_fi (A, B, f2py_A_d0, &
     &f2py_B_d0)
      integer f2py_A_d0
      integer f2py_B_d0
      real A(f2py_A_d0)
      integer B(f2py_B_d0)
      end subroutine f2pywrap_qsort_c_module_quicksort_fi 
      subroutine f2pywrap_qsort_c_module_partition_fi (A, B, marker, f2p&
     &y_A_d0, f2py_B_d0)
      integer marker
      integer f2py_A_d0
      integer f2py_B_d0
      real A(f2py_A_d0)
      integer B(f2py_B_d0)
      end subroutine f2pywrap_qsort_c_module_partition_fi 
      subroutine f2pywrap_qsort_c_module_quicksort_ii (A, B, f2py_A_d0, &
     &f2py_B_d0)
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      integer B(f2py_B_d0)
      end subroutine f2pywrap_qsort_c_module_quicksort_ii 
      subroutine f2pywrap_qsort_c_module_Partition_ii (A, B, marker, f2p&
     &y_A_d0, f2py_B_d0)
      integer marker
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      integer B(f2py_B_d0)
      end subroutine f2pywrap_qsort_c_module_Partition_ii 
      subroutine f2pywrap_qsort_c_module_quicksort_if (A, B, f2py_A_d0, &
     &f2py_B_d0)
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      real B(f2py_B_d0)
      end subroutine f2pywrap_qsort_c_module_quicksort_if 
      subroutine f2pywrap_qsort_c_module_Partition_if (A, B, marker, f2p&
     &y_A_d0, f2py_B_d0)
      integer marker
      integer f2py_A_d0
      integer f2py_B_d0
      integer A(f2py_A_d0)
      real B(f2py_B_d0)
      end subroutine f2pywrap_qsort_c_module_Partition_if
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_qsort_c_module_quicksort_fi,f2pywrap_q&
     &sort_c_module_partition_fi,f2pywrap_qsort_c_module_quicksort_ii,f2&
     &pywrap_qsort_c_module_Partition_ii,f2pywrap_qsort_c_module_quickso&
     &rt_if,f2pywrap_qsort_c_module_Partition_if)
      end subroutine f2pyinitqsort_c_module


